import 'package:the_news/model/news_article_model.dart';

final List<String> categories = [
  'All',
  'Politics',
  'Business',
  'Technology',
  'Sports',
  'Health',
  'Science',
  'Education',
  'Culture',
];

final List<ArticleModel> dummyArticles = [
  ArticleModel(
    articleId: "a1",
    link: "https://news.example.com/politics/nepal-rights",
    title: "Nepal strengthens human rights protection",
    description:
        "Government announces new measures to protect vulnerable communities.",
    content:
        "The Nepalese government has introduced new policies aimed at protecting human rights...",
    keywords: ["human rights", "policy"],
    creator: ["Nepal News"],
    language: "english",
    country: ["nepal"],
    category: ["politics"],
    datatype: "news",
    pubDate: DateTime.now().subtract(const Duration(hours: 2)),
    pubDateTZ: "UTC",
    imageUrl: "https://picsum.photos/400/200?1",
    videoUrl: null,
    sourceId: "nepalnews",
    sourceName: "Nepal News",
    sourcePriority: 1200,
    sourceUrl: "https://news.example.com",
    sourceIcon: "https://picsum.photos/40",
    sentiment: "positive",
    sentimentStats: SentimentStats(
      negative: 1.2,
      neutral: 10.3,
      positive: 88.5,
    ),
    aiTag: ["human rights"],
    aiRegion: ["nepal,asia"],
    aiOrg: null,
    aiSummary:
        "Nepal expands policies aimed at protecting vulnerable citizens.",
    duplicate: false,
  ),

  ArticleModel(
    articleId: "a2",
    link: "https://news.example.com/business/africa-startups",
    title: "African startups attract record investment",
    description: "Tech startups in Africa see major funding growth.",
    content:
        "African startups have received record-breaking investments in 2025...",
    keywords: ["startups", "investment"],
    creator: ["Business Daily"],
    language: "english",
    country: ["south africa"],
    category: ["business"],
    datatype: "news",
    pubDate: DateTime.now().subtract(const Duration(hours: 4)),
    pubDateTZ: "UTC",
    imageUrl: "https://picsum.photos/400/200?2",
    videoUrl: null,
    sourceId: "businessdaily",
    sourceName: "Business Daily",
    sourcePriority: 980,
    sourceUrl: "https://business.example.com",
    sourceIcon: "https://picsum.photos/41",
    sentiment: "positive",
    sentimentStats: SentimentStats(
      negative: 2.0,
      neutral: 15.0,
      positive: 83.0,
    ),
    aiTag: ["economy"],
    aiRegion: ["africa"],
    aiOrg: null,
    aiSummary: "African tech startups receive record funding in 2025.",
    duplicate: false,
  ),

  ArticleModel(
    articleId: "a3",
    link: "https://news.example.com/tech/ai-healthcare",
    title: "AI revolutionizes healthcare diagnostics",
    description: "Hospitals adopt AI-powered diagnostic tools.",
    content:
        "Artificial intelligence is improving accuracy and speed in healthcare diagnostics...",
    keywords: ["AI", "healthcare"],
    creator: ["Tech World"],
    language: "english",
    country: ["usa"],
    category: ["technology"],
    datatype: "news",
    pubDate: DateTime.now().subtract(const Duration(hours: 6)),
    pubDateTZ: "UTC",
    imageUrl: "https://picsum.photos/400/200?3",
    videoUrl: null,
    sourceId: "techworld",
    sourceName: "Tech World",
    sourcePriority: 500,
    sourceUrl: "https://tech.example.com",
    sourceIcon: "https://picsum.photos/42",
    sentiment: "positive",
    sentimentStats: SentimentStats(
      negative: 3.1,
      neutral: 12.4,
      positive: 84.5,
    ),
    aiTag: ["artificial intelligence"],
    aiRegion: ["global"],
    aiOrg: "WHO",
    aiSummary: "AI tools are transforming healthcare diagnostics worldwide.",
    duplicate: false,
  ),

  ArticleModel(
    articleId: "a4",
    link: "https://news.example.com/sports/world-cup",
    title: "Underdogs stun champions in World Cup clash",
    description: "A surprising victory shocks football fans worldwide.",
    content:
        "In one of the biggest upsets of the tournament, the underdogs defeated...",
    keywords: ["football", "world cup"],
    creator: ["Sports Hub"],
    language: "english",
    country: ["qatar"],
    category: ["sports"],
    datatype: "news",
    pubDate: DateTime.now().subtract(const Duration(hours: 8)),
    pubDateTZ: "UTC",
    imageUrl: "https://picsum.photos/400/200?4",
    videoUrl: null,
    sourceId: "sportshub",
    sourceName: "Sports Hub",
    sourcePriority: 720,
    sourceUrl: "https://sports.example.com",
    sourceIcon: "https://picsum.photos/43",
    sentiment: "positive",
    sentimentStats: SentimentStats(
      negative: 4.0,
      neutral: 20.0,
      positive: 76.0,
    ),
    aiTag: ["football"],
    aiRegion: ["middle east"],
    aiOrg: "FIFA",
    aiSummary: "A major upset stuns fans in the World Cup.",
    duplicate: false,
  ),

  ArticleModel(
    articleId: "a5",
    link: "https://news.example.com/environment/climate-action",
    title: "Countries agree on stronger climate action",
    description: "New commitments announced at climate summit.",
    content:
        "World leaders have agreed on more aggressive climate action targets...",
    keywords: ["climate", "environment"],
    creator: ["Green Earth"],
    language: "english",
    country: ["germany"],
    category: ["environment"],
    datatype: "news",
    pubDate: DateTime.now().subtract(const Duration(hours: 10)),
    pubDateTZ: "UTC",
    imageUrl: "https://picsum.photos/400/200?5",
    videoUrl: null,
    sourceId: "greenearth",
    sourceName: "Green Earth",
    sourcePriority: 610,
    sourceUrl: "https://environment.example.com",
    sourceIcon: "https://picsum.photos/44",
    sentiment: "positive",
    sentimentStats: SentimentStats(
      negative: 5.0,
      neutral: 25.0,
      positive: 70.0,
    ),
    aiTag: ["climate change"],
    aiRegion: ["europe"],
    aiOrg: "UN",
    aiSummary: "Nations pledge stronger climate action at summit.",
    duplicate: false,
  ),

  ArticleModel(
    articleId: "a6",
    link: "https://news.example.com/finance/markets-rise",
    title: "Global markets rally on economic optimism",
    description: "Stock markets rise amid positive economic signals.",
    content: "Investors responded positively to new economic data...",
    keywords: ["markets", "economy"],
    creator: ["Market Watch"],
    language: "english",
    country: ["usa"],
    category: ["finance"],
    datatype: "news",
    pubDate: DateTime.now().subtract(const Duration(hours: 12)),
    pubDateTZ: "UTC",
    imageUrl: "https://picsum.photos/400/200?6",
    videoUrl: null,
    sourceId: "marketwatch",
    sourceName: "Market Watch",
    sourcePriority: 430,
    sourceUrl: "https://finance.example.com",
    sourceIcon: "https://picsum.photos/45",
    sentiment: "positive",
    sentimentStats: SentimentStats(
      negative: 2.5,
      neutral: 18.0,
      positive: 79.5,
    ),
    aiTag: ["economy"],
    aiRegion: ["global"],
    aiOrg: null,
    aiSummary: "Stock markets rise due to positive economic outlook.",
    duplicate: false,
  ),

  ArticleModel(
    articleId: "a7",
    link: "https://news.example.com/health/mental-awareness",
    title: "Mental health awareness gains momentum",
    description: "Campaigns highlight the importance of mental wellbeing.",
    content:
        "Organizations worldwide are focusing on mental health awareness...",
    keywords: ["mental health"],
    creator: ["Health Today"],
    language: "english",
    country: ["canada"],
    category: ["health"],
    datatype: "news",
    pubDate: DateTime.now().subtract(const Duration(hours: 14)),
    pubDateTZ: "UTC",
    imageUrl: "https://picsum.photos/400/200?7",
    videoUrl: null,
    sourceId: "healthtoday",
    sourceName: "Health Today",
    sourcePriority: 560,
    sourceUrl: "https://health.example.com",
    sourceIcon: "https://picsum.photos/46",
    sentiment: "positive",
    sentimentStats: SentimentStats(
      negative: 1.0,
      neutral: 22.0,
      positive: 77.0,
    ),
    aiTag: ["mental health"],
    aiRegion: ["north america"],
    aiOrg: "WHO",
    aiSummary: "Mental health awareness campaigns gain global attention.",
    duplicate: false,
  ),

  ArticleModel(
    articleId: "a8",
    link: "https://news.example.com/science/space-mission",
    title: "New space mission set to explore Mars",
    description: "Scientists prepare for ambitious Mars exploration.",
    content:
        "The upcoming Mars mission aims to study the planet's atmosphere...",
    keywords: ["space", "mars"],
    creator: ["Science Daily"],
    language: "english",
    country: ["usa"],
    category: ["science"],
    datatype: "news",
    pubDate: DateTime.now().subtract(const Duration(hours: 16)),
    pubDateTZ: "UTC",
    imageUrl: "https://picsum.photos/400/200?8",
    videoUrl: null,
    sourceId: "sciencedaily",
    sourceName: "Science Daily",
    sourcePriority: 390,
    sourceUrl: "https://science.example.com",
    sourceIcon: "https://picsum.photos/47",
    sentiment: "positive",
    sentimentStats: SentimentStats(
      negative: 2.0,
      neutral: 20.0,
      positive: 78.0,
    ),
    aiTag: ["space exploration"],
    aiRegion: ["global"],
    aiOrg: "NASA",
    aiSummary: "A new mission aims to explore Mars in greater detail.",
    duplicate: false,
  ),

  ArticleModel(
    articleId: "a9",
    link: "https://news.example.com/education/online-learning",
    title: "Online learning platforms continue to grow",
    description: "Digital education adoption increases worldwide.",
    content: "Online learning platforms have seen significant growth...",
    keywords: ["education", "e-learning"],
    creator: ["Edu News"],
    language: "english",
    country: ["india"],
    category: ["education"],
    datatype: "news",
    pubDate: DateTime.now().subtract(const Duration(hours: 18)),
    pubDateTZ: "UTC",
    imageUrl: "https://picsum.photos/400/200?9",
    videoUrl: null,
    sourceId: "edunews",
    sourceName: "Edu News",
    sourcePriority: 670,
    sourceUrl: "https://education.example.com",
    sourceIcon: "https://picsum.photos/48",
    sentiment: "positive",
    sentimentStats: SentimentStats(
      negative: 3.0,
      neutral: 30.0,
      positive: 67.0,
    ),
    aiTag: ["education"],
    aiRegion: ["asia"],
    aiOrg: null,
    aiSummary: "Online education platforms see rapid global growth.",
    duplicate: false,
  ),

  ArticleModel(
    articleId: "a10",
    link: "https://news.example.com/culture/film-festival",
    title: "International film festival celebrates diversity",
    description: "Filmmakers showcase stories from around the world.",
    content: "The international film festival highlighted diverse voices...",
    keywords: ["film", "culture"],
    creator: ["Culture Wire"],
    language: "english",
    country: ["france"],
    category: ["culture"],
    datatype: "news",
    pubDate: DateTime.now().subtract(const Duration(hours: 20)),
    pubDateTZ: "UTC",
    imageUrl: "https://picsum.photos/400/200?10",
    videoUrl: null,
    sourceId: "culturewire",
    sourceName: "Culture Wire",
    sourcePriority: 510,
    sourceUrl: "https://culture.example.com",
    sourceIcon: "https://picsum.photos/49",
    sentiment: "positive",
    sentimentStats: SentimentStats(
      negative: 1.5,
      neutral: 18.5,
      positive: 80.0,
    ),
    aiTag: ["arts"],
    aiRegion: ["europe"],
    aiOrg: null,
    aiSummary: "Film festival highlights global diversity and creativity.",
    duplicate: false,
  ),
];
